"""
to_dashboard.py — publish normalized records + predictions into the dashboard.

Writes (under mi300x-dashboard/data/):
  - records/<run_id>.json          one normalized record each
  - predictions/<workload>.json    predictionSet-shaped
  - index.json                     manifest of available data
  - bundle.js                      window.MI300X_DATA = {...}  (offline, no fetch)

The dashboard's assets/data.js reads window.MI300X_DATA and overrides sim.js;
with no bundle present, sim.js remains the fallback. Pure file:// friendly.
"""
from __future__ import annotations
import json
from pathlib import Path


def _key(record):
    wl = record["meta"]["workload"]
    rc = record["meta"].get("run_config", {})
    return f"{wl.get('id')}|{wl.get('precision') or wl.get('pref')}|{wl.get('batch')}|{rc.get('numGPUs', 1)}"


def publish(dashboard_data_dir, *, records=None, prediction_sets=None,
            gem5_params=None, dataset_profile=None, train_report=None,
            device_status=None, agent_reports=None):
    data_dir = Path(dashboard_data_dir)
    (data_dir / "records").mkdir(parents=True, exist_ok=True)
    (data_dir / "predictions").mkdir(parents=True, exist_ok=True)
    records = records or []
    prediction_sets = prediction_sets or {}

    records_by_key = {}
    for r in records:
        (data_dir / "records" / f"{r['meta']['run_id']}.json").write_text(json.dumps(r, indent=2))
        records_by_key[_key(r)] = r

    for wl_id, ps in prediction_sets.items():
        (data_dir / "predictions" / f"{wl_id}.json").write_text(json.dumps(ps, indent=2))

    bundle = {
        "schema_version": "1.0.0",
        "records": records_by_key,                 # keyed "id|prec|batch|gpus"
        "predictions": prediction_sets,            # keyed workload id
        "gem5Params": gem5_params,                 # extractGem5Params shape
        "datasetProfile": dataset_profile,
        "trainReport": train_report,
        "deviceStatus": device_status,
        "agentReports": agent_reports or {},       # keyed "id|prec|batch|source"
        "generatedFrom": [r["meta"]["run_id"] for r in records],
    }
    index = {
        "records": list(records_by_key.keys()),
        "predictions": list(prediction_sets.keys()),
        "sources": sorted({r["meta"]["source"] for r in records}),
        "count": len(records),
    }
    (data_dir / "index.json").write_text(json.dumps(index, indent=2))
    (data_dir / "bundle.js").write_text(
        "/* generated by mi300x-pipeline — do not edit */\n"
        "window.MI300X_DATA = " + json.dumps(bundle) + ";\n"
    )
    return data_dir / "bundle.js"
